### ISSUE TITLE
Font rendering issue after updating to iOS 14

### ISSUE THREAD

**Issue by qeyIt** [dadap/flingon-assister#32]
I’m not certain it’s related to having updated to iOS 14, but there were no issues yesterday (before I updated my phone’s OS). Today, some of the text in English is compressed, making it a bit difficult to read. Screenshot attached, and please let me know if I can provide any more information or help. 

ps I did update manually just to see if that was the issue, but the font issue remained. 

![CC67B9EA-9A36-4F26-A8A7-42072759265B](https://user-images.githubusercontent.com/71534418/93655574-1c863b80-f9d9-11ea-844f-e287b6194cea.jpeg)

**Comment by kzzyzz** [comment]
I have the same issue. Klingon (in Roman letters) is fine, but English is scrunched up. Started when I updated to iOS 14.

**Comment by dadap** [comment]
I can confirm that this appears to be related to the iOS 14 update. I suspect it’s due to this upstream Flutter issue:

https://github.com/flutter/flutter/issues/60013

Hopefully rebuilding the app with a newer version of Flutter will be sufficient to resolve this issue. I’ll try to do that soon.

**Comment by kzzyzz** [comment]
I just updated to iOS 14.1, and the problem remains. Have you had a chance to try the newer Flutter? Thanks.

**Comment by dadap** [comment]
Sorry, it took some time to get all of the relevant parts of the toolchain updated. Rebuilding with the latest Flutter does indeed resolve the issue; however, making the fixed build available on the App Store is held up for bureaucratic reasons that I hope to have resolved soon. Marking closed, pending availability of the updated v1.1 build on the App Store.

**Comment by kzzyzz** [comment]
Thank you so much! Best of luck with the bureaucratic hassles.

**Comment by qeyIt** [comment]
Thank you so much!

**Comment by dadap** [comment]
The updated build appears to be on the App Store now. Let me know if there are any further issues.

**Comment by qeyIt** [comment]
Yes I updated it yesterday and it’s working beautifully. Thank you so much!

**Comment by kzzyzz** [comment]
Same here! majQa’! Thanks!
