### ISSUE TITLE
boQwI’ fehlen wörter

### ISSUE THREAD

**Issue by ChKargh** [dadap/flingon-assister#35]
Hallo. Ich muß mich hier leider beschweren daß der boQwI’ nicht alle deutsche wörter finden kann und das seid Tagen. Nichr böse gemeint aber das regt mich künstlich auf. Hier ein Foto.
![73487802-75EF-4867-BB6C-B03B2428E20A](https://user-images.githubusercontent.com/68635350/99874289-e89ce180-2be6-11eb-9220-b1b0d06db821.png)

**Comment by dadap** [comment]
waSbe' nIqHom. tlhIngan Hol mu' Sovbelu'chugh, 'oH ngaSlaHbe' boQwI' qawHaq.
